development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres 
  database: blog

production:
  adapter:  postgresql
  encoding: unicode
  pool:     5
  database: blog_production
  username: postgresdev
  password: postgresdev
